---
# Network Policy for Vault pods
# Restricts network access to only necessary connections
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-network-policy
  namespace: vault
spec:
  podSelector:
    matchLabels:
      app: vault
  policyTypes:
    - Ingress
    - Egress
  
  ingress:
    # Allow traffic from within namespace (for HA clustering)
    - from:
        - podSelector:
            matchLabels:
              app: vault
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
    
    # Allow traffic from application namespaces
    - from:
        - namespaceSelector:
            matchLabels:
              vault-access: "enabled"
      ports:
        - protocol: TCP
          port: 8200
    
    # Allow from default namespace (for initial setup)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 8200
  
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    
    # Allow communication between Vault pods
    - to:
        - podSelector:
            matchLabels:
              app: vault
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
    
    # Allow Kubernetes API access (for auth)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
---
# Label namespaces that should have access to Vault
# Run these commands to label your app namespaces:
# kubectl label namespace default vault-access=enabled
# kubectl label namespace apps vault-access=enabled
# kubectl label namespace production vault-access=enabled
---
# Network policy for application pods accessing Vault
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vault-access
  namespace: default
spec:
  podSelector:
    matchLabels:
      vault-enabled: "true"
  policyTypes:
    - Egress
  egress:
    # Allow access to Vault
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: vault
        - podSelector:
            matchLabels:
              app: vault
      ports:
        - protocol: TCP
          port: 8200
    
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
---
# Pod Security Policy (if PSP is enabled in your cluster)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: vault-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
---
# Role to use the PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-psp-role
  namespace: vault
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['vault-psp']
---
# Bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-psp-rolebinding
  namespace: vault
roleRef:
  kind: Role
  name: vault-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
