---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
---
# ServiceAccount for applications to authenticate with Vault
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
---
# Example: ServiceAccount for app pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-vault-access
  namespace: default
